# Generated by Django 2.1.3 on 2019-03-30 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='candidates/'),
        ),
        migrations.AlterField(
            model_name='party',
            name='symbols',
            field=models.ImageField(upload_to='symbols/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='severity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='severity_eci',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
